<#
.SYNOPSIS
    Compiles the Vulkan GLSL shaders to SPIR-V and emits them as C headers.

.DESCRIPTION
    The SPIR-V words are embedded in the source rather than shipped as files or
    compiled at runtime, for two reasons:

      * the injected payload must not load a shader compiler into someone
        else's game process, and
      * neither building nor running this repo should then require the Vulkan
        SDK - only regenerating the shaders does.

    Run this only after editing a .vert/.frag; the generated headers are
    committed.

.PARAMETER Glslang
    Path to glslangValidator.exe. Ships with the Vulkan SDK, or grab the
    standalone build from KhronosGroup/glslang releases (main-tot,
    glslang-master-windows-x64-Release.zip).
#>
[CmdletBinding()]
param(
    [string]$Glslang = $(if ($env:VULKAN_SDK) { Join-Path $env:VULKAN_SDK 'Bin\glslangValidator.exe' }
                         else { Join-Path $env:TEMP 'glslang\bin\glslangValidator.exe' })
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot

if (-not (Test-Path $Glslang)) {
    throw "glslangValidator not found at '$Glslang'. Pass -Glslang <path>, or install the Vulkan SDK."
}

# source .vert/.frag  ->  generated header, C identifier prefix
$targets = @(
    @{ Dir = Join-Path $repo 'src\GameOverlay.Avalonia.Native\shaders'
       Out = Join-Path $repo 'src\GameOverlay.Avalonia.Native\vulkan_shaders.h'
       Guard = 'overlay'; Shaders = @('overlay.vert', 'overlay.frag') }

    @{ Dir = Join-Path $repo 'src\GameOverlay.Avalonia.SampleGameVulkan\shaders'
       Out = Join-Path $repo 'src\GameOverlay.Avalonia.SampleGameVulkan\triangle_shaders.h'
       Guard = 'triangle'; Shaders = @('triangle.vert', 'triangle.frag') }
)

foreach ($t in $targets) {
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("// Generated by tools/compile-shaders.ps1 - do not edit by hand.")
    [void]$sb.AppendLine("// Regenerate after changing the .vert/.frag sources in shaders/.")
    [void]$sb.AppendLine("#pragma once")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("#include <cstdint>")
    [void]$sb.AppendLine("")

    foreach ($shader in $t.Shaders) {
        $src = Join-Path $t.Dir $shader
        $spv = Join-Path $env:TEMP ($shader + '.spv')

        Write-Host "==> $shader"
        $out = & $Glslang -V --target-env vulkan1.1 -o $spv $src 2>&1
        if ($LASTEXITCODE -ne 0) { $out | Write-Host; throw "glslang failed on $shader" }

        $bytes = [System.IO.File]::ReadAllBytes($spv)
        if ($bytes.Length % 4 -ne 0) { throw "$shader produced $($bytes.Length) bytes, not a whole number of SPIR-V words" }

        $words = New-Object uint32[] ($bytes.Length / 4)
        [System.Buffer]::BlockCopy($bytes, 0, $words, 0, $bytes.Length)

        $ti = (Get-Culture).TextInfo
        $name = 'k' + $ti.ToTitleCase($t.Guard) + $ti.ToTitleCase($shader.Split('.')[1]) + 'Spv'
        [void]$sb.AppendLine("// $shader - $($words.Count) words")
        [void]$sb.AppendLine("static const uint32_t $name`[] = {")
        for ($i = 0; $i -lt $words.Count; $i += 8) {
            $chunk = $words[$i..([Math]::Min($i + 7, $words.Count - 1))]
            [void]$sb.AppendLine('    ' + (($chunk | ForEach-Object { '0x{0:x8}' -f $_ }) -join ', ') + ',')
        }
        [void]$sb.AppendLine("};")
        [void]$sb.AppendLine("")

        Remove-Item $spv -Force -ErrorAction SilentlyContinue
    }

    Set-Content -Path $t.Out -Value $sb.ToString() -Encoding UTF8
    Write-Host "    wrote $($t.Out)"
}

Write-Host ''
Write-Host 'Shaders regenerated.'
